# Generated by Django 2.2.5 on 2019-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=15)),
                ('Data_birth', models.DateTimeField()),
            ],
        ),
    ]
